version: "3.9"

services:
  db:
    image: postgres:15
    container_name: medvault-db
    restart: always
    environment:
      POSTGRES_USER: medvault_user
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: finale
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  patients:
    build:
      context: ./patients
      dockerfile: Dockerfile
    container_name: medvault-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://medvault_user:admin123@db:5432/finale
    ports:
      - "8080:8080"
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: medvault-auth
    ports:
      - "8713:8713"  # only needed if you want to test it externally

volumes:
  postgres_data:
