version: "3.9"

services:
  db:
    image: postgres:15
    container_name: medvault-db
    restart: always
    environment:
      POSTGRES_USER: medvault_user
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: finale
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./patients
    container_name: medvault-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://medvault_user:admin123@db:5432/finale
      JWT_SECRET: supersecretkey

volumes:
  postgres_data: